sudo: false
language: java
jdk:
  - openjdk8
branches:
  only:
    - master

before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
